<div class="jumbotron">
    <h3>Cadastro de Categoria</h3>
    <form class="form-inline" action="<?php echo $this->SaveCreate() ?>" method="Post">
    <div class="form-group">
      <label for="nome">Categoria</label>
      <input type="text" class="form-control" id="nome" placeholder="Nome da Categoria" name="nome">
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
</div>
