<div class="jumbotron">
    <table class="table">
        <thead>
        <div class="">
            <h3 class="display-3">Cadastro de Categorias</h3>
            <h5><a href="<?php echo $this->getLinkAppend()?>">Nova Categoria</a></h5>
        </div>
        <tr>
            <td>Categoria</td>
            <td></td>
            <td></td>
        </tr>
        </thead>
        <?php        
        $categorias = $this->ReadAll();
        
        
        foreach ($categorias as $item):
            ?>
            <tr>
                <td><?php echo $item->nome ?></td>
                <td><a href="<?php echo $this->getLinkEdit($item->id) ?>">Alterar</a></td>
                <td><a href="<?php echo $this->getLinkDelete($item->id) ?>">Exlcluir</a></td>
            </tr>
        <?php endforeach; ?>   
    </table>
</div>
