<!DOCTYPE html>

<!-- Layout default de adminstrador
-->
<html>
    <head>
        <title><?php echo $this->title; ?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="<?php echo ROOT_VIEW ?>public/bootstrap/css/bootstrap.css" rel="stylesheet">
        <script src="<?php echo ROOT_VIEW ?>public/jquery/3.2.1/jquery.js"></script>
        <script src="<?php echo ROOT_VIEW ?>public/bootstrap/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="collapse" id="collapseExample">
            <div class="well">
                <span class="col-lg-10 right">
                    <h4 class="text-success"> <?php echo $this->message ?>
                    </h4>
                </span>
                <button class="btn btn-sm right" type="button" onclick="fechar()">
                    Fechar
                </button>
            </div>
        </div>
        <div class="container">
            <nav class='row'>
                <div class="col-xs-8">
                    <h3 class="display-3"><a href="<?php echo $this->getLinkHome() ?>">Area Administrativa</a></h3>
                </div>
                <div class="col-xs-4">
                    <a class="btn btn-primary right" href="<?php echo $this->getLinkLogin()?>" >Login</a>
                    <a class="btn btn-default right" href="<?php echo $this->getLinkLogout()?>" >Logout</a>                    
                </div>
                <hr class="m-y-2">
                <br>
            </nav>

            <?php if (!empty($this->message)) { ?>
                <script>
                    $(document).ready(function () {
                        $("#collapseExample").show();
                    });
                </script>
            <?php } ?>

            <?php $this->Render(); ?>
        </div>

        <script>
            function fechar() {
                $("#collapseExample").hide()();
            }
            ;
        </script>

    </body>
    <!--    fim-->
</html>