<div class="container">
<div class="jumbotron">
    <form action="<?php echo $this->getLinkSignIn() ?>" method="Post" class="form-inline" >
        <div class="form-group">
            <label class="sr-only" for="exampleInputEmail3">Email address</label>
            <input type="email" name="email" class="form-control" id="exampleInputEmail3" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label class="sr-only" for="exampleInputPassword3">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword3" placeholder="Password">
        </div>
         <button type="submit" class="btn btn-primary">Logar</button>
    </form>
</div>
</div>
